name: Deploy Matrix ERP

on:
  push:
    branches: [ "main", "رئيسي" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: releases/v4
          folder: .
